server:
  port: 8080

spring:
  application:
    name: smart-planner-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smart-planner}
    username: ${DB_USER:root}
    password: ${DB_PASS:admin}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  Jackson:
    serialization:write-dates-as-timestamps: false

  graphql:
    graphql:
      enabled: true
    http:
      path: /graphql

app:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS}
    accessExpMinutes: ${JWT_ACCESS_EXP_MIN:15}
    refreshExpDays: ${JWT_REFRESH_EXP_DAYS:14}

integrations:
  weather:
    baseUrl: ${WEATHER_BASE_URL:https://api.open-meteo.com}
  quote:
    baseUrl: ${QUOTE_BASE_URL:https://api.quotable.io}
app:
  integrations:
    cacheMinutes: ${INTEGRATIONS_CACHE_MIN:30}

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO


